# Site settings
title: PhotoLens
description: A photo colllection taken on trips
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: John Prefer

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://www.facebook.com/jprefer
github_url: https://github.com/jprefer
# gitlab_url: https://gitlab.com/u/jprefer
# googleplus_url: https://plus.google.com/u/0/+jprefer
instagram_url: https://www.instagram.com/jprefer/
# linkedin_url: https://www.linkedin.com/in/jprefer
# pinterest_url:
# slack_url:
twitter_url: https://twitter.com/jprefer
# Build settings
markdown: kramdown
